FROM php:8.1-fpm

# 设置时区和本地化
RUN apt-get update && apt-get install -y \
    locales \
    && locale-gen zh_CN.UTF-8 \
    && localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8

# 设置环境变量
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8

# 安装 MySQL 扩展
RUN docker-php-ext-install pdo pdo_mysql

# 复制代码到容器
COPY . /var/www/backend
WORKDIR /var/www/backend

# 设置权限
RUN chown -R www-data:www-data /var/www/backend